### ISSUE TITLE
Compilation failure (Jan 23, 2013 - Adding experimental RocketfuelMapReader..)

### ISSUE THREAD

**Issue by fqueiroz** [named-data-ndnSIM/ndnSIM#20]
Hi Alexander,
After I compile from the last update about "rocketfuel-map-reader.cc", I found some errors.
what's happening?
thanks
Flavio

../src/ndnSIM/plugins/topology/rocketfuel-map-reader.cc:
 ‘void ns3::RocketfuelMapReader::GenerateFromMapsFile(int, char**)’:

../src/ndnSIM/plugins/topology/rocketfuel-map-reader.cc:142:8: error: variable ‘dns’ set but not used [-Werror=unused-but-set-variable]

../src/ndnSIM/plugins/topology/rocketfuel-map-reader.cc:143:8: error: variable ‘bb’ set but not used [-Werror=unused-but-set-variable]

../src/ndnSIM/plugins/topology/rocketfuel-map-reader.cc: 
‘void ns3::RocketfuelMapReader::SaveTopology(const string&)’:

../src/ndnSIM/plugins/topology/rocketfuel-map-reader.cc:560:3: error: ‘auto’ will change meaning in C++0x; please remove it [-Werror=c++0x-compat]

../src/ndnSIM/plugins/topology/rocketfuel-map-reader.cc:560:8: error: ‘nodeWriter’ does not name a type

../src/ndnSIM/plugins/topology/rocketfuel-map-reader.cc:569:32: error: ‘nodeWriter’ was not declared in this scope

../src/ndnSIM/plugins/topology/rocketfuel-map-reader.cc:617:5: error: lambda expressions only available with -std=c++0x or -std=gnu++0x [-Werror]

../src/ndnSIM/plugins/topology/rocketfuel-map-reader.cc:617:6: error: no matching function for call to ‘for_each(std::listns3::TopologyReader::Link::iterator,std::listns3::TopologyReader::Link::iterator, ns3::RocketfuelMapReader::SaveTopology(const string&)::<lambda(const ns3::TopologyReader::Link&)>)’

../src/ndnSIM/plugins/topology/rocketfuel-map-reader.cc:617:6: nota: candidato é:
/usr/include/c++/4.6/bits/stl_algo.h:4373:5: nota: template<class _IIter, class _Funct> _Funct std::for_each(_IIter, _IIter, _Funct)
cc1plus: all warnings being treated as errors

**Comment by anselme333** [comment]
Dear Sir,

I am experiencing the problem of running my simulation , i keeps getting the errors from ndn-net-device-face in which i have not modified:

In file included from ./ns3/ndnSIM/model/nacc.h:22:0,
                 from ./ns3/ndn-face.h:25,
                 from ./ns3/ndn-api-face.h:29,
                 from ./ns3/ndnSIM-module.h:18,
                 from ../scratch/congestioncontrolsenario2.cc:3:
./ns3/ndnSIM/model/ndn-net-device-face.h:44:1: error: expected class-name before ‘{’ token
./ns3/ndnSIM/model/ndn-net-device-face.h:62:35: error: ‘InterestHandler’ does not name a type
./ns3/ndnSIM/model/ndn-net-device-face.h:62:52: error: ISO C++ forbids declaration of ‘interestHandler’ with no type [-fpermissive]
./ns3/ndnSIM/model/ndn-net-device-face.h:62:75: error: ‘DataHandler’ does not name a type
./ns3/ndnSIM/model/ndn-net-device-face.h:62:88: error: ISO C++ forbids declaration of ‘dataHandler’ with no type [-fpermissive]

 i have tried to re-install ndnSIM from the beginning and compilation failed. Based on below errors i  removed auto but  i still receiving errors. 
 
Before removing auto:

../utils/print-introspected-doxygen.cc: In function ‘int main(int, char**)’:
../utils/print-introspected-doxygen.cc:782:14: warning: ‘auto’ will change meaning in C++0x; please remove it [-Wc++0x-compat]
../utils/print-introspected-doxygen.cc:782:20: error: ISO C++ forbids declaration of ‘logComponent’ with no type [-fpermissive]
../utils/print-introspected-doxygen.cc:782:35: error: range-based-for loops are not allowed in C++98 mode

After removing auto:

../src/core/model/log.cc:62:20: error: ISO C++ forbids declaration of ‘i’ with no type [-fpermissive]
../src/core/model/log.cc:62:24: error: range-based-for loops are not allowed in C++98 mode
../src/core/model/log.cc:63:24: error: request for member ‘first’ in ‘i’, which is of non-class type ‘const int’
