### ISSUE TITLE
build error i am new in ndn using ubuntu 12.04

### ISSUE THREAD

**Issue by shivangigautam** [named-data-ndnSIM/ndnSIM#42]
shivangi@ubuntu:~/ndnSIM/ns-3$ ./waf --run=ndn-simple
shivangi@ubuntu:~/ndnSIM/ns-3$ ./waf --run=ndn-simple
Waf: Entering directory `/home/shivangi/ndnSIM/ns-3/build'
[ 764/1771] cxx: scratch/ndn-simple.cc -> build/scratch/ndn-simple.cc.1.o
../scratch/ndn-simple.cc: In function ‘int main(int, char**)’:
../scratch/ndn-simple.cc:31:3: error: ‘ndn’ has not been declared
../scratch/ndn-simple.cc:31:20: error: expected ‘;’ before ‘ndnHelper’
../scratch/ndn-simple.cc:32:3: error: ‘ndnHelper’ was not declared in this scope
../scratch/ndn-simple.cc:38:3: error: ‘ndn’ has not been declared
../scratch/ndn-simple.cc:38:18: error: expected ‘;’ before ‘consumerHelper’
../scratch/ndn-simple.cc:40:3: error: ‘consumerHelper’ was not declared in this scope
../scratch/ndn-simple.cc:45:3: error: ‘ndn’ has not been declared
../scratch/ndn-simple.cc:45:18: error: expected ‘;’ before ‘producerHelper’
../scratch/ndn-simple.cc:47:3: error: ‘producerHelper’ was not declared in this scope
Waf: Leaving directory`/home/shivangi/ndnSIM/ns-3/build'
Build failed
 -> task in 'ndn-simple' failed (exit status 1): 
    {task 175789516: cxx ndn-simple.cc -> ndn-simple.cc.1.o}
['/usr/bin/g++', '-O0', '-ggdb', '-g3', '-Wall', '-Werror', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-pthread', '-pthread', '-I.', '-I..', '-I/usr/include/gtk-2.0', '-I/usr/lib/i386-linux-gnu/gtk-2.0/include', '-I/usr/include/atk-1.0', '-I/usr/include/cairo', '-I/usr/include/gdk-pixbuf-2.0', '-I/usr/include/pango-1.0', '-I/usr/include/gio-unix-2.0', '-I/usr/include/glib-2.0', '-I/usr/lib/i386-linux-gnu/glib-2.0/include', '-I/usr/include/pixman-1', '-I/usr/include/freetype2', '-I/usr/include/libpng12', '-I/usr/include/libxml2', '-DNS3_ASSERT_ENABLE', '-DNS3_LOG_ENABLE', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_SQLITE3=1', '-DHAVE_IF_TUN_H=1', '../scratch/ndn-simple.cc', '-c', '-o', 'scratch/ndn-simple.cc.1.o']
shivangi@ubuntu:~/ndnSIM/ns-3$

**Comment by batoul-44** [comment]
hello everyone..i watched this valuable conversation and i hope you can help me to solve this problem....
i installed ndnSIM on ubuntu 16.04 too many times and i still have the same problem in build.... please help me
./waf

* Several tasks use the same identifier. Please check the information on
   https://waf.io/apidocs/Task.html?highlight=uid#waflib.Task.Task.uid
  - object 'SuidBuild_task' (
	{task 140598946003768: SuidBuild_task  -> }) defined in 'tap-creator'
  - object 'SuidBuild_task' (
	{task 140598946004216: SuidBuild_task  -> }) defined in 'tap-creator'
  - object 'SuidBuild_task' (
	{task 140598946004328: SuidBuild_task  -> }) defined in 'tap-creator'
  - object 'SuidBuild_task' (
	{task 140598948750392: SuidBuild_task  -> }) defined in 'tap-creator'
Waf: Leaving directory `/home/batoul/ndnSIM/ns-3/build'
Build failed
 -> task in 'ns3-ndnSIM' failed with exit status 1: 
	{task 140598943249016: cxx forwarder.cpp -> forwarder.cpp.5.o}
['/usr/bin/g++', '-std=c++14', '-O3', '-g', '-Wall', '-Wno-error=deprecated-declarations', '-fstrict-aliasing', '-Wstrict-aliasing', '-march=native', '-fstrict-overflow', '-Wstrict-overflow=2', '-std=c++14', '-fPIC', '-pthread', '-pthread', '-I.', '-I..', '-Ins3/ndnSIM/NFD', '-I../ns3/ndnSIM/NFD', '-Isrc/ndnSIM/NFD/core', '-I../src/ndnSIM/NFD/core', '-Isrc/ndnSIM/NFD/daemon', '-I../src/ndnSIM/NFD/daemon', '-Isrc/ndnSIM/NFD/rib', '-I../src/ndnSIM/NFD/rib', '-Ins3/ndnSIM', '-I../ns3/ndnSIM', '-Ins3/ndnSIM/ndn-cxx', '-I../ns3/ndnSIM/ndn-cxx', '-I.', '-I..', '-I/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent', '-I/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include', '-I/usr/lib/openmpi/include', '-I/usr/lib/openmpi/include/openmpi', '-I/usr/include', '-DNS3_BUILD_PROFILE_OPTIMIZED', '-DHAVE_SYS_IOCTL_H=1', '-DHAVE_IF_NETS_H=1', '-DHAVE_NET_ETHERNET_H=1', '-DHAVE_PACKET_H=1', '-DHAVE_MPI=1', '-DHAVE_STD_TO_STRING=1', '-DHAVE_PTHREAD=1', '-DHAVE_SQLITE3=1', '-DHAVE_OPENSSL=1', '-DHAVE_IF_TUN_H=1', '-DNS3_OPENMPI', '-DNS3_MPI', '../src/ndnSIM/NFD/daemon/fw/forwarder.cpp', '-c', '-o/home/batoul/ndnSIM/ns-3/build/src/ndnSIM/NFD/daemon/fw/forwarder.cpp.5.o']
