### ISSUE TITLE
mac install

### ISSUE THREAD

**Issue by shockjiang** [named-data-ndnSIM/ndnSIM#7]
Hi, I install ndnSIM on my mac os X 10.8 guiding by http://ndnsim.net/intro.html#downloading-ndnsim-source.
But when we run: ./waf   after ./waf configure --enable-examples --enable-ndn-plugins=topology,mobility is successful.
It turns out error:  "Could not find a task generator for the name 'ns3-visualizer'"

I think I have install gtk, goocanvas and pygraphviz, but 
"PyViz visualizer              : not enabled (Missing python modules: gtk, goocanvas, pygraphviz)"

**Comment by yan-foto** [comment]
A short update on dependencies on macOS: even though the [docs state](https://github.com/named-data-ndnSIM/ndnSIM/blob/master/docs/source/getting-started.rst) that `mac ports` is required for the visualizer, I was able to install all required dependencies as follows:

 * `brew install goocanvas pygobject3`
 * `pip install kiwisolver pygraphviz`

**disclaimer**: I don't know If its better to install everything using `pip`!

**Comment by cawka** [comment]
We are almost done with upgrading ndnSIM on top of NS-3.29 (in fact, ns-3 repo has been already rebased, just a documentation commit missing).  WIth the update, there is no longer a restriction for mac builds.

**Comment by yan-foto** [comment]
Thanks for the quick reply! I am looking forward for testing it. As of today, I still have a small problem with building (seems to be caused by `ns3`):

```
[2485/3183] Compiling src/ndnSIM/NFD/daemon/table/measurements-entry.cpp
../src/ndnSIM/model/ndn-net-device-transport.cpp:59:41: error: no member named 'GetMaxBytes' in 'ns3::QueueBase'; did you mean 'GetNBytes'?
    this->setSendQueueCapacity(txQueue->GetMaxBytes());
                                        ^~~~~~~~~~~
                                        GetNBytes
./ns3/queue.h:97:12: note: 'GetNBytes' declared here
  uint32_t GetNBytes (void) const;
           ^
1 error generated.
```
I didn't want to submit an issue, until I figure out why this happens!

**Comment by cawka** [comment]
ns-3.29 changed API a bit.  We had commit in works to fix this and I just merged it a few minutes ago.  You just need to pull latest changes of ndnSIM (in `src/ndnSIM`)

**Comment by yan-foto** [comment]
Thanks a lot! That did the trick:

```
'build' finished successfully (24m38.823s)
```

I can confirm that it build successfully on macOS Mojave.
