### ISSUE TITLE
How to measure processing delay in ndnSIM node?

### ISSUE THREAD

**Issue by pengminjiong** [named-data-ndnSIM/ndnSIM#75]
once a relay node received several  same interest packet,
process in the relay node(not sure, please check them):
 1, look up FIB  2 Keep the same interest packet in PIT  3 send out one interest packet to the publisher  4 receive data from the publisher 5 move data to cache 6 send back to the subscribers .

Is it possible to measure the processing delay(look up FIB , keep the same interest packets) in ndnSIM ?
I found simulator virtual time do not have processing delay. really need help

**Comment by cawka** [comment]
NS-3 is a discrete even simulator.  Unless you define a model which simulates the processing time, any actual function invocation takes 0 of simulation time.  In other words, it is not easy (if possible at all) simulate processing delays in NS-3 and ndnSIM.
